kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha2
metadata:
  name: imageyrotator
  namespace: imageyrotator-app
spec:
  destination:
    kind: ServiceAccount
    name: imageyrotator-service-account
    namespace: imageyrotator-app
  rules:
    - kind: HTTPRouteGroup
      name: imageyrotator-service-routes
      matches:
        - api
  sources:
    - kind: ServiceAccount
      name: frontend-service-account
      namespace: imageyrotator-app
---
apiVersion: specs.smi-spec.io/v1alpha3
kind: HTTPRouteGroup
metadata:
  name: imageyrotator-service-routes
  namespace: imageyrotator-app
spec:
  matches:
    - name: api
      methods: ["*"]
      pathRegex: "/api/.*"
