apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: imageyrotator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-service-account
      containers:
        - image: terravenil/imageyrotator-fronend:v1.0
          name: frontend
          env:
            - name: API_URL
              valueFrom:
                  configMapKeyRef:
                    name: imageyrotator-config
                    key: api_url
          ports:
            - containerPort: 3000
              name: http
